In [1]:
# Suppressing "INFO" and "WARNING" messages by setting the verbosity of both the Transformers and TensorFlow libraries.
from transformers import logging
logging.set_verbosity_error()
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
from transformers import BertTokenizer, BertModel

In [3]:
model = BertModel.from_pretrained('bert-base-multilingual-cased') 

In [4]:
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased') 

In [5]:
sentence = "C'est une si belle journée"

In [6]:
inputs = tokenizer(sentence, return_tensors="pt")

In [7]:
print(inputs)

{'input_ids': tensor([[  101,   140,   112, 10176, 10231, 10294, 40094, 16947, 10238, 82091,
         10112,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [8]:
objects = model(**inputs)
hidden_rep = objects.last_hidden_state
cls_head = objects.pooler_output

In [9]:
print(hidden_rep)

tensor([[[ 0.2788,  0.3578,  0.0943,  ...,  0.3915,  0.0082,  0.0844],
         [ 0.3886,  0.2666,  0.5883,  ...,  0.0863, -0.2773, -0.3116],
         [-0.2430,  0.2498,  0.9914,  ...,  0.4468, -0.7415, -0.0033],
         ...,
         [-0.1003,  0.6098, -0.3139,  ...,  0.6421, -0.3278,  0.3517],
         [ 0.4329, -0.0163,  0.7720,  ...,  0.1304,  0.1172,  0.2630],
         [ 0.6394,  0.4822,  0.7073,  ...,  0.4524,  0.0581,  0.2114]]],
       grad_fn=<NativeLayerNormBackward0>)


In [10]:
print(cls_head)

tensor([[ 0.4139,  0.0176,  0.3462, -0.2360, -0.2655,  0.5479,  0.2022,  0.2364,
         -0.4844,  0.4132, -0.0365, -0.2775, -0.2060, -0.1788,  0.2506, -0.2341,
          0.7934,  0.0842, -0.1262, -0.4389, -1.0000, -0.1552, -0.3454, -0.1286,
         -0.4762,  0.1129, -0.2150,  0.1704,  0.2074, -0.0889, -0.0216, -1.0000,
          0.6392,  0.8052,  0.2476, -0.1107,  0.1216,  0.2955,  0.2290, -0.3996,
         -0.2054,  0.0716, -0.1115,  0.2674, -0.2027, -0.3824, -0.1221,  0.1705,
         -0.3700,  0.1942, -0.0094,  0.2950,  0.4697,  0.3277,  0.3540,  0.3499,
          0.3113,  0.2992,  0.3708, -0.1501, -0.0121,  0.4286,  0.3545, -0.0799,
         -0.2921, -0.4317,  0.1252, -0.0764,  0.6050, -0.1293, -0.2309, -0.4413,
         -0.1333,  0.2752,  0.1758, -0.2952,  0.3434,  0.3568, -0.0385, -0.2304,
         -0.3927, -0.5797, -0.3644,  0.0930, -0.0610,  0.2829,  0.2972, -0.4662,
          0.2358, -0.0978,  0.3498,  0.6234, -0.2119,  0.4120, -0.1866, -0.2166,
         -0.8979, -0.0668, -

In [12]:
print(hidden_rep.shape)
print(hidden_rep[0][10])

torch.Size([1, 12, 768])
tensor([ 4.3292e-01, -1.6254e-02,  7.7204e-01,  1.7409e-01,  9.8742e-02,
         2.8776e-01, -6.2960e-01, -3.2027e-01, -9.8393e-02,  6.7434e-01,
         5.2281e-01,  4.7785e-01,  5.5721e-01,  1.4558e+00,  3.8106e-01,
         6.4551e-02, -1.1857e-01,  2.0036e-01, -8.6213e-03, -8.9975e-01,
        -3.5368e-01,  1.1199e+00, -3.5930e-01,  2.7644e-01, -2.8632e-01,
         1.5248e-01,  8.5400e-02,  2.5755e-01,  3.5270e-01, -3.6699e-01,
         3.5527e-01,  2.0452e-02, -3.7845e-01,  6.4188e-02,  5.4894e-01,
         1.0590e-02, -4.3101e-01, -2.2711e-01, -3.9992e-01,  3.2894e-01,
         4.1934e-01, -1.4018e-01, -5.9338e-01, -2.8422e-02,  5.6592e-01,
         5.5333e-03,  4.4227e-01, -4.7517e-01, -3.8356e-01, -4.3268e-01,
         7.7676e-01,  1.7064e-02, -2.4699e-01,  7.5841e-02, -1.3029e-01,
         1.8116e-01,  6.1157e-02, -7.5673e-01,  4.2309e-02, -7.3674e-01,
         3.8232e-01, -2.6068e-01,  6.7871e-03,  1.2976e-01,  5.1602e-01,
        -8.5853e-02, -6.68

In [13]:
sentence = "Es ist so ein wunderschöner Tag"

In [14]:
inputs = tokenizer(sentence, return_tensors="pt")

In [15]:
print(inputs)

{'input_ids': tensor([[  101, 10912, 10298, 10380, 10290,   191, 56354, 10943, 10269, 81692,
         10129, 17033,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [16]:
objects = model(**inputs)
hidden_rep = objects.last_hidden_state
cls_head = objects.pooler_output

In [17]:
print(hidden_rep)

tensor([[[ 0.2849,  0.1101,  0.2505,  ...,  0.3427,  0.0357, -0.0144],
         [ 0.1195, -0.1368,  1.1755,  ...,  0.3875,  0.3713, -0.2653],
         [-0.1030,  0.0869,  0.0060,  ...,  0.8986,  0.2657,  0.2018],
         ...,
         [-0.2486, -0.2986,  0.2538,  ...,  0.4554,  0.5084, -0.6171],
         [ 0.3742, -0.0138,  0.9294,  ...,  0.5763,  0.2588, -0.2648],
         [ 0.5743,  0.0857,  1.0585,  ...,  0.3276,  0.0686, -0.0972]]],
       grad_fn=<NativeLayerNormBackward0>)


In [18]:
print(hidden_rep.shape)
print(hidden_rep[0][5])

torch.Size([1, 13, 768])
tensor([ 5.4656e-01,  3.2057e-01,  2.2282e-01,  3.6872e-01,  2.9447e-01,
         4.9098e-01, -9.7564e-01, -9.8845e-02,  6.8332e-01,  8.8929e-01,
        -2.3419e-01,  1.7837e-01,  3.2992e-01,  3.1188e-01, -2.1730e-01,
         1.8272e-01,  5.7619e-01, -1.3103e-01, -1.6273e-01, -1.2355e-01,
        -1.2193e-01,  4.6964e-01, -9.7600e-01, -2.3696e-01,  5.0719e-02,
         1.1431e+00, -3.4420e-01, -2.7873e-01, -6.3815e-01, -1.1345e+00,
         1.3816e-01,  7.4534e-01,  8.6691e-02,  8.9094e-01, -5.7841e-01,
         1.6770e-01,  2.0966e-01,  8.0675e-02,  3.6674e-01, -6.2049e-01,
        -5.4953e-01, -1.6294e-01, -2.5513e-01,  5.8450e-02,  1.0373e+00,
         4.3968e-01,  1.3472e-01, -5.8612e-01,  4.3114e-01, -1.3033e+00,
        -1.4194e+00, -4.3079e-01, -2.5351e-01, -9.4332e-01, -1.1974e-01,
         6.1489e-01,  1.9387e-01, -3.5555e-01,  8.8159e-01, -1.6723e-01,
        -2.2158e-01, -3.8138e-01, -1.1432e-01, -3.8916e-01, -1.0108e+00,
        -5.6437e-01,  3.90

In [19]:
print(cls_head)

tensor([[ 3.3568e-01, -2.5698e-02,  3.0671e-01, -8.7827e-02, -1.6925e-01,
          5.2650e-01,  2.2123e-01,  1.0746e-01, -4.9005e-01,  4.4047e-01,
          1.1718e-01, -1.5915e-01, -2.2644e-01, -1.4793e-01,  9.5706e-02,
         -3.8607e-01,  6.5055e-01,  8.2183e-02,  1.2028e-01, -2.8696e-01,
         -9.9998e-01, -3.1806e-02, -3.0740e-01, -7.4556e-02, -3.1126e-01,
          6.3096e-02, -1.4721e-01, -1.7538e-02,  1.0114e-01, -1.4124e-01,
          1.6733e-02, -9.9998e-01,  6.7069e-01,  7.0602e-01,  1.3061e-01,
         -1.0223e-02,  1.1995e-01,  2.5762e-01,  2.6577e-01, -3.2901e-01,
         -1.3251e-01, -1.6658e-03, -1.3378e-01,  1.3184e-01, -1.7498e-01,
         -2.9388e-01, -1.2186e-01,  2.2021e-01, -3.7862e-01,  5.2574e-02,
          8.4775e-02,  2.8688e-01,  4.7693e-01,  4.1017e-01,  3.0897e-01,
          1.9102e-01,  1.4102e-01,  1.8686e-01,  3.1225e-01, -4.9504e-02,
         -2.9951e-02,  2.6237e-01,  1.5994e-01, -8.0792e-02, -2.1418e-01,
         -3.4559e-01,  9.6126e-03, -9.